### ISSUE TITLE
Copyrighted content from johnkavanagh.co.uk

### ISSUE THREAD

**Issue by johnkavanagh** [yasirov/cv#1]
Hi Anton.

You've copied the Privacy Policy [from my personal website](https://johnkavanagh.co.uk/privacy/) into this project here:
https://github.com/yasirov/cv/blob/a1953e59283b2497810d68bddc878038c01fd3fe/src/policy.html

This even still retains several references back to my site at johnkavanagh.co.uk, screenshots of this are attached.

You'll have received notice at the time you copied this that it was copyrighted and not for reuse, which is also clearly sign posted on the site itself.

Could I ask that you please remove this (in it's entirety) as you do not have permission to use it.

<img width="921" alt="Screenshot 2022-12-16 at 09 15 12" src="https://user-images.githubusercontent.com/2272755/208064695-535157e1-48a7-4d13-9759-a35279a1eab4.png">

<img width="955" alt="Screenshot 2022-12-16 at 09 15 22" src="https://user-images.githubusercontent.com/2272755/208064683-25d7419e-6acd-4476-aa48-d4a1197d5cf7.png">

**Comment by yasirov** [comment]
Good afternoon! I apologize for the inconvenience, I was sure that this
will not appear in the search results and will not be displayed anywhere. I
used it purely for practice purposes, since I just started my training.
Right now I'll make any necessary changes and promise it won't happen
again. Thank you! Have a great day!

пт, 16 дек. 2022 г. в 10:18, John Kavanagh ***@***.***>:

**Comment by johnkavanagh** [comment]
Thank you.  Good luck with your training!
